apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-application
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "mummu.common.labels" . | indent 4 }}
data:
  application.properties: |-
    # Spring Actuator
    management.server.port= {{ .Values.common.service.internalPort }}
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus
    management.metrics.distribution.percentiles-histogram.http.server.requests=true

    # Logging
    logging.level.no.entur.mummu={{ .Values.configMap.logLevel }}

    # spring boot
    # Enable response compression and http2
    server.compression.enabled=true
    server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    server.compression.min-response-size=1024
    server.http2.enabled=true

    # disable swagger runtime
    no.entur.mummu.swagger.host.url={{ .Values.configMap.hostUrl }}
    springdoc.api-docs.enabled=false
    springdoc.swagger-ui.enabled=false

    # stop place data 
    no.entur.mummu.data-file=/tmp/netex_data.zip

    # stop place updater
    no.entur.mummu.stopplacesupdater.enabled=true
    org.rutebanken.helper.stopplace.changelog.enabled=true
    org.rutebanken.helper.stopplace.changelog.kafka.bootstrap-servers={{ .Values.configMap.stopplace.changelog.kafka.bootstrapServers }}
    org.rutebanken.helper.stopplace.changelog.kafka.schema-registry-url={{ .Values.configMap.stopplace.changelog.kafka.schemaRegistryUrl }}
    org.rutebanken.helper.stopplace.changelog.kafka.security-protocol=SASL_SSL
    org.rutebanken.helper.stopplace.changelog.kafka.sasl-mechanism=SCRAM-SHA-512
    org.rutebanken.helper.stopplace.changelog.kafka.sasl-jaas-config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKAUSERNAME}" password="${KAFKAPASSWORD}";
    org.rutebanken.helper.stopplace.changelog.kafka.schema-registry-basic-auth-user-info=${KAFKAUSERNAME}:${KAFKAPASSWORD}
    org.rutebanken.helper.stopplace.changelog.kafka.topic={{ .Values.configMap.stopplace.changelog.kafka.topic }}
    org.rutebanken.helper.stopplace.changelog.repository.url={{ .Values.configMap.stopplace.changelog.repository.url }}
    spring.main.allow-bean-definition-overriding=true
