apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
  application.properties: |-
    # Spring Actuator
    management.server.port=9001
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus

    # Logging
    logging.level.no.entur.mummu={{ .Values.configMap.logLevel }}

    # spring boot
    # Enable response compression and http2
    server.compression.enabled=true
    server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    server.compression.min-response-size=1024
    server.http2.enabled=true

    # swagger
    springdoc.api-docs.path=/api-docs
    no.entur.mummu.swagger.host.url={{ .Values.configMap.hostUrl }}

    # Kafka
    entur.kafka.kafkaCluster={{ .Values.configMap.kafkaCluster }}
    entur.kafka.avroSerializableClasses=org.rutebanken.irkalla.avro.StopPlaceChangelogEvent
    entur.kafka.consumer.enabled=true
    entur.kafka.consumer.offsetReset=earliest
    entur.kafka.consumer.enableAutoCommit=false
    entur.kafka.producer.enabled=false
    spring.kafka.listener.ack-mode=manual
    entur.kafka.sasl.username=${KAFKAUSERNAME}
    entur.kafka.sasl.password=${KAFKAPASSWORD}

    # mummu
    no.entur.mummu.data-file=/deployments/netex_data.zip
    no.entur.mummu.tiamat.url={{ .Values.configMap.tiamatUrl }}
    no.entur.mummu.changelog.topic={{ .Values.configMap.changelogTopic }}
    
