apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "app.name" . }}-redeploy-cronjob-day
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "mummu.common.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
      {{- include "mummu.cron-job-template" . | indent 8 }}
  schedule: 0 13 * * *
  successfulJobsHistoryLimit: 3
  suspend: false

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "app.name" . }}-redeploy-cronjob-night
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "mummu.common.labels" . | indent 4 }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
      {{- include "mummu.cron-job-template" . | indent 8 }}
  schedule: 0 5 * * *
  successfulJobsHistoryLimit: 3
  suspend: false