common:
  configmap:
    data:
      NETEX_DATA_URL: https://storage.googleapis.com/marduk-dev/tiamat/Full_latest.zip
  env: dev
  replicas: 1

configMap:
  logLevel: DEBUG
  hostUrl: https://api.dev.entur.io/stop-places/v1/read
  stopplace:
    changelog:
      kafka:
        bootstrapServers: entur-kafka-test-ext-entur-test.aivencloud.com:11877
        schemaRegistryUrl: https://entur-kafka-test-ext-entur-test.aivencloud.com:11867
        topic: ror-stop-place-changelog-dev
      repository:
        url: https://api.dev.entur.io/stop-places/v1

ingress:
  domainName: .dev.entur.io

cronJob:
  gcpProject: entur-dev-gcp2
  slackUrl: ror-dev-slack-url
