common:
  configmap:
    data:
      NETEX_DATA_URL: https://storage.googleapis.com/marduk-test/tiamat/Full_latest.zip
  env: tst
  replicas: 1

configMap:
  logLevel: INFO
  hostUrl: https://api.staging.entur.io/stop-places/v1/read
  stopplace:
    changelog:
      kafka:
        bootstrapServers: entur-kafka-test-ext-entur-test.aivencloud.com:11877
        schemaRegistryUrl: https://entur-kafka-test-ext-entur-test.aivencloud.com:11867
        topic: ror-stop-place-changelog-staging
      repository:
        url: https://api.staging.entur.io/stop-places/v1

ingress:
  domainName: .staging.entur.io

cronJob:
  gcpProject: entur-test-gcp2
  slackUrl: ror-staging-slack-url


