common:
  app: mummu
  shortname: mummu
  team: ror
  ingress:
    enabled: false
  service:
    externalPort: 80
    internalPort: 8080
  container:
    image: <+artifacts.primary.image>
    cpu: 1
    memory: 5200
    memoryLimit: 5200
    probes:
      liveness:
        path: /actuator/health/liveness
      readiness:
        path: /actuator/health/readiness
    prometheus:
      enabled: true
      path: /actuator/prometheus
    volumeMounts:
      - mountPath: /etc/application-config
        name: application-config
        readOnly: true
    volumes:
      - configMap:
          defaultMode: 420
          name: mummu-application
        name: application-config
  postgres:
    enabled: false
  configmap:
    data:
      JDK_JAVA_OPTIONS: -server -Xmx4096m -Xss1024m -Xms4096m -Dspring.config.location=/etc/application-config/application.properties
        -Dfile.encoding=UTF-8
      TZ: Europe/Oslo
    enabled: true
    toEnv: true
  secrets:
    kafka: [KAFKAPASSWORD, KAFKAUSERNAME]
    slack: [SLACK_URL]
cronJobImage: eu.gcr.io/entur-system-1287/deployment-rollout-restart:0.1.12
