replicas: 1

rollingUpdate:
  maxSurge: 2
  maxUnavailable: 1

resources:
  cpuLimit: 1
  memLimit: 5Gi
  cpuRequest: 1
  memRequest: 5Gi
  xss: 1024m
  xms: 4096m
  xmx: 4096m

configMapMount:
  name: mummu-config

image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

service:
  http:
    externalPort: 80
    internalPort: 8080

ingress:
  enabled: true
  devIp: 35.195.223.29
  stagingIp: 35.195.146.93
  productionIp: 35.187.15.14

horizontalPodAutoscaler:
  maxReplicas: 2
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
